---
hocs-backend-service:
  minReplicas: 1
  maxReplicas: 1

  deploymentAnnotations:
    downscaler/downtime: "Mon-Sun 00:00-07:55 Europe/London,Mon-Sun 18:05-24:00 Europe/London"

  app:
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
